CMS_HOST: studio.temp.local
CMS_OAUTH2_SECRET: EdQM130OjNlwTRyjgBB6FrhJ
ELASTICSEARCH_HOST: https://vpc-openedx-z2idkesqa6gd5cqjkeogvofg4m.us-east-1.es.amazonaws.com
ELASTICSEARCH_PORT: 443
ENABLE_HTTPS: false
ENABLE_WEB_PROXY: false
ID: KzPOgdfr6g1E73mguISCEmvF
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEogIBAAKCAQEA/IaceNReOIHIEqaw4otZBwUCV0SfdXJioWQv6MiW1c5MApqy

  AdNYJgjE6pfxU8D0JMnyNxtkACUw9VJJO+wHDtnbYCJaQz/zj+1ljEQwFuUsFD+3

  3IlmCChkKQh8HNoBoq8aKQJVi3O7UCf2MxmhPkYDbr1jNit7reWOlWWrDdcYpPGm

  BxbR6Y6yyHcrCHzZfosm7WIjby5De+ZC0xs+kFHCOPcsPrJ8ONV+lbSQgoK24hCM

  ElJtd2q4luVzxAXwN5DU/8AsLporp/Mr+30iTpChVJx2hrLwOHsw3YltVGOr6Fvf

  ydeywdTaugahmvDW5UyMcqx7ZFqAoQrj/BBEtQIDAQABAoH/I5pvdD+YsPZXP/ll

  5rjt029qeLsUel/CAuZCnKOG63L2x+AGrtSd1WPf7moNkcYzZ4Kr07KXyoGWYLN1

  tOrgy/YIDR8wa7z3bA5nicexkcQ/VAu1MvpDPzWnZDinrKgBmrHY+ZMl8HyuWmRI

  7jz01DtbWIHlPpts7JRIsi4ua3cuWNVd6srd6qY0TVGB2JYi/uNInsY0cRWLljV2

  l5R2RFadFDm8IjAheRudZ3Y5ediWUX3llL6TOdGICeriBkXk7ejG31Q6iCjH1VyE

  MYQzSecIY0f/fDGhnYZYZAisaLgu/bRFlvzESEDgYw5AlTyEnl9uJ2XbxBqXFkyL

  dtsVAoGBAP4o+CgkdwP3hJsaRA30MmdHe52XqnwABDFVs9WRyKH/SKRKJbzpm80A

  DxtXG0tdZ8eqn4DsZsiryQMJHsRd7+qc8xn8rbgeRTBMF1MMo8OuJb3P4Vv5DQT4

  rGiuKLEUiA7ebJz/Nq+4J6YDgtW2A8kgf3+uzqi8k4aA6aR3KhN7AoGBAP5anPqX

  8BKorJr2JcAAJ5wmEk9vIIx0Ljo7LHDD+nWllATRdqFAAxdrfmmMSWUr1Ir3SV8U

  Wx2idGmA5Wr7YxOhDojQOJLooSglAYE9nmSvM6qNGlYe16vkVDOZXPWRcGTWL8fW

  w2hT6eUgglgdCy23vEJvXL0ymo8Ewfg52zmPAoGAatCfEofYuQMSaPkN9utVL5Cc

  RCwUi06adH13Od+t+V9HkTxURePMBcjrkGr4XqEf14s+w7kWrWl87lir5I0yImDZ

  zmciP0oBe/3Oo6mhPcD3vaEbLkMqFJfKJahkE5/0WoNiFE0yF4GGsD+zgcugJawR

  yYCW+9VdDt8o0mT+evcCgYEAw83XuKXMX2DP9z70EplL5M3+HH5MzTMG/zbcYDbO

  EVEU4JyrOTkA6D+NAg3H1oVmSlBRgEs4VVjhSvK6KaA6Rjse6D16v8Urgq7yOJ7J

  13J0UJ/tHU0C9EWCeHJgeH6sykOEZs+ygBbRINzk2pYJK/mciHwYJWHWT7D27XME

  i4sCgYEA8OQRygnxXxIiQ89Bzf2lzuKbq+M5bnNzEHfTn8WMlUrtIukQgFCSpMJg

  EDa5urjQTYWWVMTBU9iOnW03Zfgar36QWO7x4qUXwws/Z5rFdTJHXbUYY7XY0cr8

  CIvhkN9LM2yTWitqBlf7lpoDPuwX2IRHmkl7rrzz8J8oPFA87pE=

  -----END RSA PRIVATE KEY-----'
K8S_NAMESPACE: openedx
LMS_HOST: temp.local
MEILISEARCH_API_KEY: 02316be97d651afcd9ead6b7f27e4dce11e2500443f3effa1016469d5b53c867
MEILISEARCH_API_KEY_UID: 31530085-d546-477d-a6c0-246634ddb908
MEILISEARCH_MASTER_KEY: jePlzHrsWbpD7d67zZpxkrnk
MONGODB_AUTH_SOURCE: admin
MONGODB_DATABASE: openedx
MONGODB_HOST: openedx-docdb.cluster-cyrgyqyk0ln1.us-east-1.docdb.amazonaws.com
MONGODB_PASSWORD: JKZDPipJBBZS8ETL1vZCanBThQ1j53xB
MONGODB_PORT: 27017
MONGODB_USERNAME: docdbadmin
MONGODB_USE_SSL: true
MYSQL_HOST: openedx-mysql.cyrgyqyk0ln1.us-east-1.rds.amazonaws.com
MYSQL_PORT: 3306
MYSQL_ROOT_PASSWORD: JVyEbEYj2fI0LEAzafnWZ67X0wC0957Q
MYSQL_ROOT_USERNAME: admin
OPENEDX_MYSQL_PASSWORD: VErFLgly
OPENEDX_SECRET_KEY: 77z5RGsE17VjwODWzLAO7uBP
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
REDIS_HOST: openedx-redis.gawkfy.0001.use1.cache.amazonaws.com
REDIS_PORT: 6379
RUN_ELASTICSEARCH: false
RUN_MONGODB: false
RUN_MYSQL: false
RUN_REDIS: false
RUN_SMTP: false
