CMS_HOST: studio.temporary.local
CMS_OAUTH2_SECRET: EMeyc72fvEHifoRw6Ysr1jzA
ELASTICSEARCH_HOST: https://vpc-openedx-z2idkesqa6gd5cqjkeogvofg4m.us-east-1.es.amazonaws.com
ELASTICSEARCH_PORT: 443
ENABLE_HTTPS: false
ENABLE_WEB_PROXY: false
ID: oldTGDTENlkg0GBMNm4aTyNU
JWT_RSA_PRIVATE_KEY: '-----BEGIN RSA PRIVATE KEY-----

  MIIEpAIBAAKCAQEAwCNZZK9aQgO89pGGJ0A9TWQ2Gdz1tsK8QmLW6wZpzhLl9RK+

  NUrinE8lc5bds0/t6xdTU5Kzgj5CiQYx7jeOtItrXMIXl1xPPeNtRJZVl9NvKcy0

  vImJY6cafZqzd5fbGjNDmwZAwK5/c5OSpDu0Q4ik+VJxKQxqjtloROt114RGOiA/

  bB/B3M4tOvv6yQ1Jwfpy8Dh7DS+DYX7qGMkVRsCIzecfUZNTWrnwoaD1DP+3ux1D

  PN7Qk0PTHiicGTjUfo7xLHdbiTzNlUTtUlJZZuDie3e+9GuXZoLHyIM1kYz9Vc2x

  LXoRk+qjuUDCXYMZIfJnN1V/OCJeUPE/ixO+KQIDAQABAoIBAAr5ie03xz9JkN/W

  9fN51naRoIskz/kxkYjLi1dPMrh1Y7gLqxyGq5Uo6oH6I62OxXoonIHDzv1DxU+n

  2wQZHXg1FXvDJLn9073nJsePPGeIyXWjrngtdVD2oMtSDJRqcrasp8eBWYNYBEor

  q1Q2X9MoCTT/j0dRtlLKBXbC/08WctNW74MPLJZm3AM80fw6wA8TVVGkFNxPaKwL

  RVxnzsa48GZltOrlkdFctWPOlYvr7lN2UPFuN3OHK92A0NQjcZaUUbjwMecaKfEt

  wQCc9JMnaxZIXqjfDYaj94cWH+nLKSBLrprrTsIzgEvRPJ14CaG4zTGa9uqYWGcO

  EhZcVi0CgYEAwvMqhUHsRFFXXMn6xpmXT+D2TWhegCd407nKUBTXx/40SSdqOfB8

  4m+3TtsTWHZkUeKqqMYUA8Awl+ZguVdCa1N2qVddQ/9y72r1Brog5Kb3+ypkwRqu

  riqTbccGAPcgqfZwjw6cBXg8iFqa13s0CtWbIKDUC/ABiLIbza4SzC0CgYEA/E7E

  P4fccmXzsbk0OletzjbtvusMK4zsbBec46rPzvchT9oipkv8TActmIOKqfmAX7Ql

  u1XhrYbMZsBO53CJBDX6+S0AaYZmGw03neWpQERKM49SCWWo5GZOheOsZ1uCDLWP

  sHMAGmZ9IvHO8s76p3AvklUj0lum4Ne6R6Isa20CgYBIZCOV+DTT6aCXRClrNf2K

  G+9aLzdoP0AO3x7RPewix7KCt7Aqc7LsIq/fCFrWrp/yCEl3ApbMDcH9pf6k1FJF

  qGiX2Wk4ptL3NLBoHxW30oijK8reKhpTclvsl8sS8LGga3LArJwjK9LOj1aQTZ+1

  pjxEkXQsOqNXL0xDxDAWwQKBgQCRFeI3/jI//mxyCGQGIKErcd6o6JSo/nJ9fd6T

  9IdnJikbt/4wzoUYWxBXIV09fOHbJsaDwVDy7g7gDznQUKAZscjOPJh+FfDlIWaX

  /5aiBCL/Hy03hiPmowYIa/GZxb80+7rS5m5qwAC5dX9hlLACVLqmVRsyPc3qgWL3

  CkSsyQKBgQCNFDTTZbwU8NP/eOt7V6QNDcTVYmOlnmlFhbw+1Hi8JnsX9knAls7U

  HYa6trhYjfmdayqyyA1AAytm/xH1zw00ec8tluQFqaNNJtoStZJAUG0+lUBCbS8+

  ZWL72hK9iYT3saNnuttisk/WN7UJVhlivta7qRiXA1HlA82XhBpoUA==

  -----END RSA PRIVATE KEY-----'
K8S_NAMESPACE: openedx
LMS_HOST: lms.temporary.local
MEILISEARCH_API_KEY: 43fd8e0bf623244cc8c9bc9dce4450d56d0fa4671c20682408c980c06d60d144
MEILISEARCH_API_KEY_UID: 42067a88-99db-440d-882c-4c54863a3fc0
MEILISEARCH_MASTER_KEY: VHWOmxH8jopKufVbDvOjMvm5
MONGODB_AUTH_SOURCE: admin
MONGODB_DATABASE: openedx
MONGODB_HOST: openedx-docdb.cluster-cyrgyqyk0ln1.us-east-1.docdb.amazonaws.com
MONGODB_PASSWORD: EOhKLdymGbV3gi5z5OnEqVRNKpaz9uUI
MONGODB_PORT: 27017
MONGODB_USERNAME: docdbadmin
MONGODB_USE_SSL: true
MYSQL_HOST: openedx-mysql.cyrgyqyk0ln1.us-east-1.rds.amazonaws.com
MYSQL_PORT: 3306
MYSQL_ROOT_PASSWORD: PVJgYmMXbF20xW02qd6v7yNh13kYCJqL
MYSQL_ROOT_USERNAME: admin
OPENEDX_MYSQL_PASSWORD: whLejfrG
OPENEDX_SECRET_KEY: L8uyxW2ZJ71xDAK84O8w5L55
PLUGINS:
- mfe
- indigo
PLUGIN_INDEXES:
- https://overhang.io/tutor/main
- https://overhang.io/tutor/contrib
REDIS_HOST: openedx-redis.gawkfy.0001.use1.cache.amazonaws.com
REDIS_PORT: 6379
RUN_ELASTICSEARCH: false
RUN_MONGODB: false
RUN_MYSQL: false
RUN_REDIS: false
RUN_SMTP: false
